### ISSUE TITLE
BNS Name transfer failing

### ISSUE THREAD

**Issue by Eshwari007** [blockstack/stacks-wallet-web#1845]
PR:https://github.com/blockstack/stacks-wallet-web/pull/1827
https://btc-website.tintashlabs.com/
User was testing bns with several accounts and all went well.
User then tried to transfer a bns name to another account and received the following error
<img width="459" alt="Screen Shot 2021-10-19 at 11 22 50 AM" src="https://user-images.githubusercontent.com/38872890/137948424-0cc98218-c948-4f5a-ba0b-bd9d36bbd0c1.png">
https://explorer.stacks.co/txid/0xcdbe856a282b8a4a1412e9f65a22bc219cd138122e5b99dca8027335d61af332?chain=testnet

<img width="370" alt="Screen Shot 2021-10-19 at 11 59 02 AM" src="https://user-images.githubusercontent.com/38872890/137948464-c9088bdf-746f-4a77-8f42-a6b4b961b219.png">
 cc @kyranjamie @fbwoolf @beguene

**Comment by markmhendrickson** [comment]
The error and transaction failure here appear unrelated? In that the former is a matter of the wallet not being able to "find" the web app anymore upon submission (perhaps the tab was closed). Whereas the latter is a problem with the transaction itself, and presumably the contract logs could distinguish which problem.

I'm closing this out either way since it doesn't appear the wallet has an issue here.
