### ISSUE TITLE
Transaction amount + fee still exceeding address' total balance causing pending issues

### ISSUE THREAD

**Issue by Hero-Gamer** [blockstack/stacks-wallet-web#3338]
Hi all, just would like to highlight that the problem of being able to spend more than your balance issue, please see below example, new user contacted me today.
It is causing many new users coming to Stacks very confused I have seen many examples recently not just this. 

It was a swap on ALEX, does it have to do with ALEX UI at all? Maybe some collab needed to resolve this issue? Nevertheless, I still think the wallet should not allow u to transfer more than amount + fee. 

Is there something we can do about that?
Thank you

<img width="207" alt="image" src="https://user-images.githubusercontent.com/92864860/222512526-7578be8e-5259-474e-b3d9-efb0c028f541.png">

<img width="385" alt="image" src="https://user-images.githubusercontent.com/92864860/222512744-be181121-7175-4aa5-b1a1-3b1bb7bfe166.png">

<img width="306" alt="image" src="https://user-images.githubusercontent.com/92864860/222512634-69962575-29bb-445b-821f-5694af783c0f.png">

![image](https://user-images.githubusercontent.com/92864860/222513101-d42ec44f-7edc-4962-a0cd-22d776dced9b.png)

![image](https://user-images.githubusercontent.com/92864860/222513262-1e3ebfde-d3b8-42ec-8af1-af52f67d4d59.png)

**Comment by 314159265359879** [comment]
@Hero-Gamer thanks for reporting Hero!

I have noticed this too. It is especially causing issues for new users. 

I think the wallet can do better at checking pending transactions and take into account pending STX transfers (based on post conditions for example) regular STX transfers and fees. In addition when users increase fees, the wallet should check if the balance (adjusted with pending transfers/fees) is sufficient.

This issue is related:
https://github.com/hirosystems/stacks-wallet-web/issues/3109

**Comment by Hero-Gamer** [comment]
problem still not solved as of today: 
<img width="817" alt="image" src="https://user-images.githubusercontent.com/92864860/228021794-68601db8-6c4f-4fa4-b7bf-8aaab5f13ce8.png">

<img width="1118" alt="image" src="https://user-images.githubusercontent.com/92864860/228022006-aa2001b2-170c-40f2-aa92-257353bc937a.png">

nonce 1.

**Comment by alter-eggo** [comment]
@Hero-Gamer we cannot fix the exact issue in Alex ui via our codebase. merged pr is fixing the same problem in our stx send form
